#!/usr/bin/env bash

module load python/3.6.3
module load tabix


python3 spheus.py --vcf inputs/phASER_GTEx_v8_merged.vcf.gz --expr /home/nehsan/data/rnaseq/Adipose_Subcutanous/correctedPeerFactor_allRows_GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads_normal.csv.gz --eqtl inputs/samplesdf.tsv --output newcovar.csv --isnorm 1 --islog 1 


