#!/usr/bin/env bash

module load python/3.6.3
module load tabix


python3 spheus.py --vcf inputs/phASER_GTEx_v8_merged.vcf.gz --expr /home/bkotis/spheus/inputs/deseq_expressions_adipose_header.csv.gz  --eqtl inputs/Adipose_Subcutaneous.v8.independent_eqtls.txt.afc --output gold_standard_Adipose.tsv --isnorm 1 --cov inputs/Adipose_Subcutaneous.v8.covariates.txt  


